### ISSUE TITLE
[Request] Please stop being a jew

### ISSUE THREAD

**Issue by jewblock** [chrisaljoudi/uBlock#1451]
![plz stop](https://cloud.githubusercontent.com/assets/9098352/8137385/f5246c24-113a-11e5-8653-4e2445d6fd1f.png)

**Comment by CrisBRM** [comment]
I can't wait to be accused of doing this.
Ironically, Chris is the one who got shadowbanned on plebbit a week after the split for having multiple accounts. :^]

**Comment by jewblock** [comment]
:^]

**Comment by jewblock** [comment]
Does this mean the issue has been resolved?

**Comment by chrisaljoudi** [comment]
@jewblock it means a more-than-sufficient amount of shits has been wasted on this.
