### ISSUE TITLE
Support Legal Action

### ISSUE THREAD

**Issue by Soret** [chrisaljoudi/uBlock#1699]
17tHV6hgSP8uJmiuGVLHHeeVKJGwUmQte8

Donate Bitcoins to this address (or any altcoins via shapeshift.io) to support the uBlock Origin community's course to oust out the mole from the hole, we will send this bitch behind jail for stealing people's money. Continued support is required afterwards to pay for all court fees in the Russian Federation.

**Comment by chrisaljoudi** [comment]
Your behavior has been reported to GitHub.
