### ISSUE TITLE
Support Legal Action

### ISSUE THREAD

**Issue by Soret** [chrisaljoudi/uBlock#1700]
17tHV6hgSP8uJmiuGVLHHeeVKJGwUmQte8

Donate Bitcoins to this address (or any altcoins via shapeshift.io) to support the uBlock Origin community's course to oust out the mole from the hole, we will send this bitch behind jail for stealing people's money. Continued support is required afterwards to pay for all court fees in the Russian Federation and the United States of America.

**Comment by chrisaljoudi** [comment]
I think it is amusing, to say the least, that you're asking for donation money to sue me for accepting donations.
