### ISSUE TITLE
I think it is hilarious such a bitch you are, for stealing people's money for something you do not own.

### ISSUE THREAD

**Issue by Soret** [chrisaljoudi/uBlock#1701]
-

Donate Bitcoins to this address (or any altcoins via shapeshift.io) to support the uBlock Origin community's course to oust out the mole from the hole, we will send this bitch behind jail for stealing people's money. Continued support is required afterwards to pay for all court fees in the Russian Federation and the United States.

**Comment by chrisaljoudi** [comment]
I'm going to keep this gem open as evidence for when GitHub reviews the report. Have a nice day!
